#!/bin/bash -eu
#
# Copyright © 2017 Samuel Holland <samuel@sholland.org>
# See LICENSE in the project directory for license terms.
#
# bash is required for regular expression matching.
#

# Adjust these as needed
ARCH=or1k
CALL_INSN="l.jal"
TAIL_INSN="l.j"

# Generated, but might need adjustment
CROSS_COMPILE=${ARCH}-linux-musl-

# Command-line parameters
input_file=$1
output_file=$2

# Internal variables
caller=unknown

cat > "$output_file" << "EOF"
strict digraph calls {
  layout = dot
  node [height = 1, shape = box]
  rankdir = TB
  ratio = 0.2
  splines = ortho
EOF
grep -F -e '>:' -e "$CALL_INSN" -e "$TAIL_INSN" "$input_file" |
while read -r line; do
  if [[ $line =~ ^[[:xdigit:]]{8}\ \<([[:alnum:]_]+)\>:$ ]]; then
    caller=${BASH_REMATCH[1]}
    printf '  %s\n' "$caller" >> "$output_file"
  elif [[ $line =~ ^.*${CALL_INSN}\ [[:xdigit:]]+\ \<([[:alnum:]_]+)\>$ ]]; then
    [[ ${BASH_REMATCH[1]} = __udivsi3 || ${BASH_REMATCH[1]} = printf ]] && continue
    printf '  %s -> %s\n' "$caller" "${BASH_REMATCH[1]}" >> "$output_file"
  elif [[ $line =~ ^.*${TAIL_INSN}\ [[:xdigit:]]+\ \<([[:alnum:]_]+)\>$ ]]; then
    [[ ${BASH_REMATCH[1]} = __udivsi3 || ${BASH_REMATCH[1]} = printf ]] && continue
    printf '  %s -> %s [style = dashed]\n' "$caller" "${BASH_REMATCH[1]}" >> "$output_file"
  fi
done
printf '}\n' >> "$output_file"
